### ISSUE TITLE
Duplicated logs when sending messages in productive deployment

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Messaging-Services#191]
Using v4.1.1.1. Dataspace Connector in PRODUCTIVE_DEPLOYMENT mode. No explicit log settings for the messaging services.

I get the following logs when sending a message: [20210630_log.txt](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services/files/6739935/20210630_log.txt)

Seems like there are some duplicated logs. Maybe you could also take a look at this. I have no idea what I can do differently to fix this. Anyway, the logs are not coming from the DSC.

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
I could imagine that parts of the logs come from the Dataspace Connector.

The Dataspace Connector uses HTTP-Tracing, which also print log-info, I can't tell exactly when though, would need to be further investigated:
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/src/main/java/io/dataspaceconnector/filter/httptracing/HttpTraceEventHandler.java#L48

The normal log history produced by the messaging-services look as follows and without duplicates, so there is no `INFO - Ok Http Client Protocols[h2, http/1.1]` as in the logs attached to the issue:
![image](https://user-images.githubusercontent.com/75306992/123971962-c3612480-d9ba-11eb-92fd-070396fa3156.png)

Since I can't recreate the problem, I'm putting it on hold for now, but will continue to monitor.
