### ISSUE TITLE
Provide infomodel version

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Messaging-Services#249]
Hi! As you now provide a possibility to access the connector id from the certificate, could you maybe also provide an interface for accessing the current infomodel version? Or set it youself as outbound model version in the configuration model. But as we now have our own configuration entity in the DSC, it would be cleaner if we could just access the information - and then pass it to the messaging services. Of course it would be also nice, if you could provide the inbound versions, but I am not sure who should take care of compatibility checks, the messaging services library, the infomodel library, or the connector itself. Currently, we are setting more or less random values, as there is no Infomodel compatibility table or something like that.

**Comment by tmberthold** [comment]
I had already thought about this and experimented a bit in the Messaging-Services. However, the bottom line is that I would like to see this be a functionality in the infomodel artifacts themselves, so that they return their current version and compatible versions via a method call. We as Messaging-Services can't know which infomodel artifact versions are compatible with which other infomodel artifact versions. We could at most return the currently used version based on the version number of the dependency in the pom. However you could do the same via a META-INF query of the used transitive dependencies of the build jar/image of the DSC directly as well, again I would rather like the artifacts to return their current version and compatible versions directly instead of the Messaging-Services doing this for them.

@maboeckmann @stefkoslowski

**Comment by tmberthold** [comment]
Will close it here as it is a feature request for the artifacts, an issue/feature request was opened there.
