### ISSUE TITLE
DapsValidator - JWT expired

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-Messaging-Services#351]
I sometimes have this error in the logs:

```
/connector_1 log="2021-11-09 15:40:19,343 https-jsse-nio-8080-exec-10 ERROR de.fraunhofer.ids.messaging.core.daps.DapsValidator - JWT expired at 2021-11-09T15:40:12Z. Current time: 2021-11-09T15:40:19Z, a difference of 7343 milliseconds.  Allowed clock skew: 0 milliseconds." thread=https-jsse-nio-8080-exec-10 severity=ERROR message="de.fraunhofer.ids.messaging.core.daps.DapsValidator - JWT expired at 2021-11-09T15:40:12Z. Current time: 2021-11-09T15:40:19Z, a difference of 7343 milliseconds.  Allowed clock skew: 0 milliseconds."
```

Why is this happening? The communication fails in this case.

**Comment by sebplorenz** [comment]
Hi Tim, I had a second look into the logs. It seems that the connector is complaining about its own token. Could it be that before sending a request to another connector it gets its own token from the DAPS, checks it and realizes that the token is too old? In this case there is a clock skew of 7 seconds between the connector and the DAPS.

**Comment by tmberthold** [comment]
Hi, the +7 seconds then fit to the log message from above `difference of 7343 milliseconds`.

I am not aware that we do a validation, however I can find the following reference in the DAPS specification regarding sending the request token for a DAT to the DAPS at _Request token that is handed in at DAPS side_: "If the system time [of the connector] is not in synch with the DAPS, the request token will be rejected (e.g., nbf [not before] is in the future)."

**Comment by sebplorenz** [comment]
Hi, after checking the logs again I realized that the failing communication (as stated at the beginning) had another reason. It seems that the clock skew error is not a real error. I see that after the error message the AisecTokenManagerService is downloading a new token which works.
My explaination for the error is the following now. Since the job is running every hour I assume that the token has a validity of 1h (which seems quite long). When the job starts again it checks the old token it has cached and realizes that the token is too old. It throws an error message and handles the situation by downloading a new token.
But since the situation is already handled (because it is expected that the token can be expired), no error message should be thrown in this case.

**Comment by tmberthold** [comment]
If it should be only about the pure log message, then we cannot easily prevent it, since it is not thrown by the Dataspace Connector itself or the Messaging-Services at all.

To read the claims of the cached DAT to get the expiration we use the Jwts.parser() (io.jsonwebtoken.Jwts), which unfortunately checks before us whether the tokenvalue is valid at all. For example, if it has expired, the parser throws an ExpiredJWTException on the one hand and logs a message that we cannot control on the other. We catch the exception and get a new token or in case of no exception we execute our own validation afterwards and then get a new one depending on the result.

**The only way without this log would be to not use the parser at all at this point. For this we would have to read the claims directly when we receive the DAT from the DAPS and save them additionally to the complete JWT, such as the info of the expiration date, which should still be valid directly after receipt. By that we would be able to access the info directly when checking if the DAT has expired instead of having to re-read the claims and using the parser.**

**Comment by tmberthold** [comment]
_(have implemented the solution to also cache the expiration date directly after fetching the DAT next to the DAT itself, instead of reading the claims via the parser every time a message is sent and thus running into the error-log)_
